/*
If we list all the natural numbers below 10 that are multiples of 3 or 5, 
we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
*/

var sum = 0;
var limit = 1000;
    for(var i = 1; i < limit; i++){
        if(i % 3 === 0){
            sum += i;
        }
        else if(i % 5 === 0){
            sum += i;
        }
    }
    
console.log(sum);

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

var z =0;
var numbers = [1,2];
var evensum=0;
var limit2=1000;

for(var k=2; k<limit2;k++)
  {
    numbers.push(numbers[k-2]+numbers[k-1]);
   
    if(numbers[k]%2===0)
      {
        evensum+=numbers[k];
      }
  }

console.log(evensum);

/*


*/

